### PR TITLE
Power - Directory Capitalization

### LINKED ISSUE #318: Power - /control.lua:5 module gui.gui not found;
Power - /control.lua:5 module gui.gui not found
no such file -Power _ _/gui/gui.lua 
no such file [Factorio]/data/core/gui/gui.lha

No mods but Dytech core, machines, power and war active.  Game loads but this error when clicking generate.

### PR DESCRIPTION
**Pull request by JLBShecky**
When accessing the mod in it's zip form file paths are case sensitive.

Closes #318

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Or on better OSs that do not screw with naming like the poor Windows file systems do; proper casing is always important.

**Comment by JLBShecky** [comment]
Well some times you have to make concessions between ease of use for new users (ignoring case) and power. That said trying to get git to accept the rename on my end was a monumental task/learning experience for me. I still think that I should have been able to rename it in one commit, but I couldn't get github to actually take the changes properly. I may have to try a different git client and see if that would make a difference, although it could just be a weakness of git on windows.

**Comment by OvermindDL1** [comment]
Actually you can do it via the official git client on windows by:
```
git mv path/To/oldName path/to/newname
```
:-)

**Comment by OvermindDL1** [comment]
And true yeah, but Factorio was not programmed with case insensitivity in mind, so always have to make sure case is correct.

**Comment by JLBShecky** [comment]
Actually the git mv was the first thing that I tried, and it was not even registering that I had made a change.

Even after I turned on the option to not ignore case it still wasn't able to do it in one commit. everything looked fine on my end until I pushed it to github, then I had two copies of the files one in 'GUI' and one it 'gui'. I game up at that point and just split it into two commits.

If you want to make a PR that does it in one commit I would have no issues closing this one, not that it would really matter in the long run I'd think, but it would keep things cleaner I guess.

**Comment by OvermindDL1** [comment]
Nah, yours is fine, but if you really care about doing only one commit instead of two then look into the `git squash` command.  :-)

**Comment by MagicLegend** [comment]
Those cases. Who created those sTraNgE thInGs? WeLl, thank you for fixing my derp. I never noted the problem cuz' I always use the folder instead of the zip.

**Pull request merged**
